name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - name: Build
        run: uv build
      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        run: uv publish
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*.whl
